# Generated by Django 3.0.5 on 2020-04-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='update',
            new_name='updated',
        ),
    ]
